### ISSUE TITLE
Use of ctags

### ISSUE THREAD

**Issue by mulderp** [michaelbaisch/uDino-Preprocessor#1]
Hi!

I saw your note in https://github.com/sudar/Arduino-Makefile/issues/59 - and tried the preprocessor with Ruby.

For a quick check, I wanted to use the MacOS X default ctags, and run:

```
ruby preprocessor.rb blinkLED leornado-blink
```

However, the script fails here:

```
# Is project folder an Arduino project?
projectName = 'standarfirmata' # projectFolder.split("/").last

# if Dir["#{File.expand_path("#{projectFolder}#{projectName}#{arduinoExtensions}")}"].length() == 0 then
#   abort "Project folder doesn't look like an Arduino project folder"
# end
```

So, I commented it out. But the command did not yet work.

So, I just tried ctags with the argument list, but it gives:

```
ctags --language-force=c++ --c++-kinds=pf --fields=KSTtzn project/standard_firmata.ino
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
```

**Comment by michaelbaisch** [comment]
There is a patched version of ctags in _/bin/_ which is used by the preprocessor.

The Arduino project should have, in your case, at least this structure: _blinkLED/blinkLED.ino_ (partent folder with the same name as the main .ino file)
By commenting this part you skipped this test. 
Is the project _blinkLED_ in this regard a "valid" Arduino project?
What's not working after you commented it out?
